# @package _global_
defaults:
  - /trainer: default
  - /loader: default
  - /dataset: dna_segment
#    Available options in 'task':
#      lm
#      multiclass_classification
#      multilabel_classification
#      regression
  - /task: multiclass_classification
  - /optimizer: adamw
  - /scheduler: plateau
  - /callbacks: [base, checkpoint]

train:
  monitor: val/accuracy # Needed for plateau scheduler
  mode: max

encoder: id

# we need this for classification!
decoder:
  _name_: sequence
  mode: pool
